version: 2
updates:
  - package-ecosystem: npm
    directory: /examples/angular
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
    commit-message:
      prefix: "chore"
      include: scope
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: /examples/react-cra
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
    commit-message:
      prefix: "chore"
      include: scope
    versioning-strategy: increase
  - package-ecosystem: npm
    directory: /examples/react-gatsby
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
    commit-message:
      prefix: "chore"
      include: scope
    versioning-strategy: increase


